### ISSUE TITLE
Support the OR operator in queries.

### ISSUE THREAD

**Issue by colemanw** [civicrm/api4#11]
They syntax could easily get messy. Need to think of a clean-ish way to support groupings of AND and OR.

**Comment by JoeMurray** [comment]
Don't forget NOT. See Search builder for an ancient attempt to serve power users.

**Comment by eileenmcnaughton** [comment]
Drupal DB query has an OR object that you attach. It doesn't feel intuitive but maybe it's a good model for all that

**Comment by xurizaemon** [comment]
For CiviCRM using its own API internally as a query builder, I think this all makes sense.

When we expose the API to external clients, I feel uncomfortable about our API being an SQL builder, because we're exposing a lot more surface to attackers to pry on when we provide direct SQLisms such as `LIKE`, `OR`, `AND`, `NOT`. (Compared with API queries being limited to simple entity filters by matching parameter.)

I understand that historically CiviCRM has exposed a lot of SQLism, that the application is deeply SQL-ish, and that *not* offering this would be a big challenge. But I want to check in and see whether we can approach this in a way which improves our security.

Here I see CiviCRM's API trying to do things other APIs typically don't, which makes me wonder if a unique approach is a good idea. Are there good examples of other web APIs which expose SQL params so directly?

**Comment by xurizaemon** [comment]
Actually - I'll move that to a separate issue #41, so discussion can continue on `OR` without philosophical intervention.

**Comment by ErichBSchulz** [comment]
@colemanw - I think we can close this now
