### ISSUE TITLE
too many get classes??

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/api4#3]
I can understand the need for 2 `Get` classes (I guess) but is 3 really necessary? 

```
     ./Civi/API/V4/Action/Get.php:40:class Get extends API\V4\Action             
     ./Civi/API/V4/Entity/Entity/Get.php:34:class Get extends Action             
     ./Civi/API/V4/Entity/Participant/Get.php:34:class Get extends \Civi\API\V4\Action\Get                                                                       
```

**Comment by colemanw** [comment]
I understand it is confusing. To explain:

There is only one base class `Get` which extends the base-er class `Action`
All but the most generic Apis will extend `\Civi\API\V4\Action\Get` (the really basic ones don't need to extend it at all).

The "Entity" api however is a special case. It needs its own `Get` class because it is a "meta" api. It is the api of the api, and promotes peace, love, and understanding of the entire api cosmos.

As we start to add more entities than just Participant, it will make more sense. Want to help get started?

**Comment by ErichBSchulz** [comment]
doh! oh I get it the entity entity is an entity - sorry probably could have figured this out

yes very keen to help! sorry I have much to lean about civi internals and the v3 API. I am also hoping for some feedback on [these crazy ideas](https://docs.google.com/document/d/1N_kGR2LHLcLFk0eBAv7Ac-v9Ry3nADMue3sfnSaIZMg/edit?usp=sharing) at some point

**Comment by colemanw** [comment]
Perhaps we could make it less confusing by naming the `Entity` api something else?

**Comment by ErichBSchulz** [comment]
mmm - I like the idea of `entity` being an entity - which actually makes me think the name is fine - it also makes me think there should be a `civicrm_entity` table/DAO/BAO ???

**Comment by ErichBSchulz** [comment]
although that maybe just crazy talk
