### ISSUE TITLE
fluent name, what's the benefit of the verbs?

### ISSUE THREAD

**Issue by tttp** [civicrm/api4#50]
Hi,
The example code is

```
\Civi\Api4\Contact::get()
  ->setSelect(['id', 'sort_name'])
  ->addWhere('contact_type', '=', 'Individual')
  ->addOrderBy('sort_name', 'DESC')
  ->setCheckPermissions(TRUE)
  ->execute();
```

what are the benefits of the "set" and "add" orefix? Wouldn't removing them make it simplier?
it might be a non native issue, but I would as happily use setWhere or addSelect. ie. that prefix feels that it can be either, and I wouldn't know the rule of deciding which one I'm supposed to put.

either clarifying, or simply removing them:

```
\Civi\Api4\Contact::get()
  ->Select(['id', 'sort_name'])
  ->Where('contact_type', '=', 'Individual')
  ->OrderBy('sort_name', 'DESC')
  ->CheckPermissions(TRUE)
  ->execute();
```
 
or (more active record style)

\Civi\Api4\Contact
  ->Select(['id', 'sort_name'])
  ->Where('contact_type', '=', 'Individual')
  ->OrderBy('sort_name', 'DESC')
  ->CheckPermissions(TRUE)
  ->get();
```

**Comment by JoeMurray** [comment]
I have an aversion to confusion between add and set prefixes, but would prefer to see one of them to neither. I don't like the third style in terms of where the get() goes, and the lack of an execute. IIRC in Drupal using earlier style, one can prep the query, maybe pass it to a hook, and only then execute it - a strong advantage.

**Comment by nganivet** [comment]
AFAIK the prefixes are needed because of the default behaviors, ie. when 
searching for a contact, the default is to exclude deleted contacts (ie. 
is_deleted = 0).

So that criteria is added to the Where clause by default. If the user 
needs to add other criteria, the function addWhere needs to be called 
(ie. we're adding these criteria on top of whatever is already there). 
If on the other side we want to replace this criteria, for example to 
search only the deleted contacts, we should use setWhere. Hence having 
both prefixes / functions being necessary.

Coleman can probably provide more details on this if needed.

------ Original Message ------

**Comment by JoeMurray** [comment]
That's a clear distinction that makes sense for a query object that might be manipulated prior to use or re-use. Thanks, Nicolas.

**Comment by xurizaemon** [comment]
> what are the benefits of the "set" and "add" prefix? Wouldn't removing them make it simplier?

If I understand @nganivet correctly:

* *where* may exist as internal method
* *addOrderBy*, *addWhere* - appends to existing select, where values
* *setSelect*, *setCheckPermissions* - overwrites existing select, checkpermissions values

So the ordering precedence for this statement would result in `ORDER BY sort_name DESC, display_name`, eg first in first out? Wondering what other details of syntax might need to be clarified.

    \Civi\Api4\Contact::get()
      ->setSelect(['id', 'sort_name', 'display_name'])
      ->addWhere('contact_type', '=', 'Individual')
      ->addOrderBy('sort_name', 'DESC')
      ->addOrderBy('display_name', 'ASC')
      ->execute();

**Comment by ErichBSchulz** [comment]
Yes as @xurizaemon says.

**Comment by mickadoo** [comment]
Closing this as the comments explained the syntax.
