### ISSUE TITLE
Autoloading does not work for custom PHPUnit base-classes

### ISSUE THREAD

**Issue by mickadoo** [civicrm/api4#59]
I've seen some comments in the tests like this:

> // fixme - what am I doing wrong to need this line?
require_once 'UnitTestCase.php';

I guess it's because the tests aren't in the "Civi" directory. After messing around a bit I have an idea that the Civi stuff is autoloaded properly because of the Civix namespace in `info.xml`.

I think having tests as a top level folder is the right approach, and would even like to put them in a different namespace root. To do this it seems like we should just be able to add to the `classloader` attribute in `info.xml`.

But when adding the classloader to the info.xml it seems to add it to the autoloader's `prefixesPsr0` instead of PSR-4 as the XML indicates.

The only composer PSR-4 prefix I see in the instantiated autoloader is:

`Civi\\Cxn\\Rpc\\ => /path/to/civicrm/vendor/civicrm/civicrm-cxn-rpc/src`

In addition it doesn't seem to use the extension directory for the path. For example when I add new classloader mapping it just uses the CiviCRM root at the relative path root, for example adding:

```<psr4 prefix="Civi\" path="tests" />```

To the extension `info.xml` will produce the following PSR-0 mapping in the autoloader:

```
"Civi" => "/path/to/civicrm/tests/phpunit"
```

But of course I don't plan to add my code to the CiviCRM root.

I don't think we can fix this without a core change (unless I've understood the root of the problem).

Edit:
I think maybe I had the wrong idea and custom namespaces from info.xml are not loaded in the tests, but it would be nice if they were.

**Comment by totten** [comment]
1. Clarification: The `classloader` in `info.xml` is processed via https://github.com/civicrm/civicrm-core/blob/master/CRM/Extension/ClassLoader.php#L103 . This uses the same class+function as composer (esp ` \Composer\Autoload\ClassLoader::setPsr4()`), but it configures the classloader using a different source of data (`info.xml` files and the `civicrm_extension` statuses).

2. Clarification: The issue is specifically with *base-classes/traits/interfaces* defined by extensions for headless PHPUnit tests. The autoloader does work once the test is running. It also works in E2E testing. It also works if the base-class/trait/interface is defined in core.

3. The particular flavor of class-loading (`include_path` for `CRM_*`; or PSR-0 or PSR-4; `composer.json` or `info.xml`) isn't really the issue. (Please believe that I played with multiple arrangements...) The issue is that *the class-loader is conditional, depending upon the content of the database*. Any scheme in which the classloader can be activated/deactivated based on the Civi DB will pose the same issues. For a longer explanation, see https://civicrm.stackexchange.com/questions/15810/does-class-autoloading-not-work-in-standalone-phpunit-testing

4. After re-reading that StackExchange comment, an improvement might be this: move the `require_once` statement into `tests/phpunit/bootstrap.php`. This would (a) resolve the aesthetic issue of sprinkling file-paths into code and (b) not depend on the database and (c) not require complicated reorg.

**Comment by mickadoo** [comment]
Thanks for the information @totten 

I was making more tests, traits and abstract classes for API4 and didn't like always adding require statements. I tried this in the bootloader and it's working for me:

```
$bootCode = cv('php:boot --level=classloader', 'phpcode');
eval($bootCode);

preg_match('/require_once\s*\'(.*)\'/', $bootCode, $matches);
$loader = require(sprintf('%s/vendor/autoload.php', $matches[1]));
$loader->add('', __DIR__);
```

**Comment by totten** [comment]
OK, that does seem better than needing to register each one.

Suggestion: instead of using `preg_match()` and `$matches[1]` to find the CiviCRM source tree, try `$GLOBALS["civicrm_root"]`. That should be more robust against trivial changes in the `php:boot` output.

**Comment by mickadoo** [comment]
I had a look for some superglobal I could use here, but `$GLOBALS["civicrm_root"]` doesn't seem to be set at this point.

**Comment by mickadoo** [comment]
Closing since this is working now. Please re-open if there is some other suggestion for how to obtain the civicrm_root.
